-- 02_schema_and_seed.sql
-- 在 LAB 连接里执行：创建表结构并填充数据（带倾斜分布，方便后续调优）

-- ===== 可调数据量（需要更大就改这里）=====
DEFINE N_CUSTOMERS = 1000
DEFINE N_PRODUCTS  = 5000
DEFINE N_ORDERS    = 5000   -- 100万
DEFINE COMMIT_EVERY = 1000

-- =========================================

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT Dropping old tables if exist...
BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN ('ORDER_ITEMS','ORDERS','PRODUCTS','CUSTOMERS')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS PURGE';
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT Creating tables...
CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(80),
  email       VARCHAR2(120),
  region      VARCHAR2(20),
  created_at  DATE DEFAULT SYSDATE
);

CREATE TABLE products (
  product_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku         VARCHAR2(30),
  category    VARCHAR2(30),
  price       NUMBER(10,2),
  created_at  DATE DEFAULT SYSDATE
);

CREATE TABLE orders (
  order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  NUMBER NOT NULL,
  order_date   DATE   DEFAULT SYSDATE,
  status       VARCHAR2(20),
  total_amount NUMBER(10,2),
  CONSTRAINT fk_orders_cust FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
  item_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    NUMBER NOT NULL,
  product_id  NUMBER NOT NULL,
  qty         NUMBER NOT NULL,
  unit_price  NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_items_order   FOREIGN KEY (order_id)   REFERENCES orders(order_id),
  CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

PROMPT Seeding data...
DECLARE
  n_customers     PLS_INTEGER := TO_NUMBER('&&N_CUSTOMERS');
  n_products      PLS_INTEGER := TO_NUMBER('&&N_PRODUCTS');
  n_orders        PLS_INTEGER := TO_NUMBER('&&N_ORDERS');
  commit_every    PLS_INTEGER := TO_NUMBER('&&COMMIT_EVERY');

  v_order_id      NUMBER;
  sum_amount      NUMBER;
  items_per_order PLS_INTEGER;
  price           NUMBER;
  pid             NUMBER;
  qty             NUMBER;
BEGIN
  -- customers：区域倾斜（80% 在 Kanto）
  FOR i IN 1..n_customers LOOP
    INSERT INTO customers(name, email, region, created_at)
    VALUES (
      'Cust '||i,
      'cust'||i||'@example.com',
      CASE
        WHEN DBMS_RANDOM.VALUE(0,1) < 0.8 THEN 'Kanto'
        WHEN DBMS_RANDOM.VALUE(0,1) < 0.9 THEN 'Kansai'
        ELSE 'Kyushu'
      END,
      SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0,365))
    );
  END LOOP;
  COMMIT;

  -- products：类目倾斜
  FOR i IN 1..n_products LOOP
    INSERT INTO products(sku, category, price, created_at)
    VALUES (
      'SKU'||TO_CHAR(i,'FM000000'),
      CASE
        WHEN DBMS_RANDOM.VALUE(0,1) < 0.7 THEN 'Electronics'
        WHEN DBMS_RANDOM.VALUE(0,1) < 0.9 THEN 'Home'
        ELSE 'Books'
      END,
      ROUND(DBMS_RANDOM.VALUE(5,800),2),
      SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0,365))
    );
  END LOOP;
  COMMIT;

  -- orders + order_items（每单 1~5 个商品），并回填订单金额
  FOR i IN 1..n_orders LOOP
    INSERT INTO orders(customer_id, order_date, status, total_amount)
    VALUES (
      TRUNC(DBMS_RANDOM.VALUE(1, n_customers + 1)), -- 包含上限
      SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0,365)),
      CASE WHEN DBMS_RANDOM.VALUE(0,1) < 0.85 THEN 'PAID' ELSE 'PENDING' END,
      0
    )
    RETURNING order_id INTO v_order_id;

    sum_amount := 0;
    items_per_order := 1 + TRUNC(DBMS_RANDOM.VALUE(0,4)); -- 1..5
    FOR j IN 1..items_per_order LOOP
      pid := TRUNC(DBMS_RANDOM.VALUE(1, n_products + 1)); -- 包含上限
      SELECT price INTO price FROM products WHERE product_id = pid;
      qty := 1 + TRUNC(DBMS_RANDOM.VALUE(0,4));
      INSERT INTO order_items(order_id, product_id, qty, unit_price)
      VALUES (v_order_id, pid, qty, price);
      sum_amount := sum_amount + qty * price;
    END LOOP;

    UPDATE orders SET total_amount = sum_amount WHERE order_id = v_order_id;

    IF MOD(i, commit_every) = 0 THEN
      COMMIT;
    END IF;
  END LOOP;

  COMMIT;
END;
/

-- 输出汇总信息（不要在 PUT_LINE 里写子查询）
DECLARE
  c_cnt NUMBER; p_cnt NUMBER; o_cnt NUMBER; i_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO c_cnt FROM customers;
  SELECT COUNT(*) INTO p_cnt FROM products;
  SELECT COUNT(*) INTO o_cnt FROM orders;
  SELECT COUNT(*) INTO i_cnt FROM order_items;

  DBMS_OUTPUT.PUT_LINE('✅ Seed finished: '
    || c_cnt || ' customers, '
    || p_cnt || ' products, '
    || o_cnt || ' orders, '
    || i_cnt || ' items.');
END;
/
PROMPT Done.

-- 快速验收（F5 执行会依次输出）
PROMPT === Quick Check ===
SELECT COUNT(*) AS customers FROM customers;
SELECT COUNT(*) AS products  FROM products;
SELECT COUNT(*) AS orders    FROM orders;
SELECT COUNT(*) AS items     FROM order_items;

-- 为后续调优演示，刻意不创建任何二级索引、也先不收统计信息
